#!/bin/bash
echo "OSI Model Layers:"
echo "1. Physical - Cables, hubs"
echo "2. Data Link - Switches, MAC addresses"
echo "3. Network - Routers, IP addresses"
echo "4. Transport - TCP/UDP"
echo "5. Session - NetBIOS, RPC"
echo "6. Presentation - Encryption, compression"
echo "7. Application - HTTP, DNS, FTP"
echo ""
echo "TCP/IP Model Layers:"
echo "Link - Physical + Data Link"
echo "Internet - Network (IP)"
echo "Transport - TCP/UDP"
echo "Application - HTTP, DNS, etc."
